name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:humble
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2_timer/
          cd /root/ros2_ws
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y
          colcon build
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          ./src/ros2_timer/test/test.bash /root
